name: Build (Dev Branch Only)

concurrency:
  group: development
  cancel-in-progress: true

on:
  push:
    branches: [ dev ]

jobs:
  build-only:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
